language: node_js
node_js:
  - "8.9.1"

before_install:
  - git config --global push.default matching
  - git config --global user.name "wangduanduan"

install:
  - yarn global add hexo-cli
  - yarn

script:
  - hexo clean
  - hexo g

after_success:
  - cd ./public
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$BLOG@github.com/wangduanduan/wangduanduan.github.io.git master

branches:
  only:
    - gh-pages
cache:
  directories:
    - node_modules